// Copyright (C) 2005-2010 Code Synthesis Tools CC
//
// This program was generated by CodeSynthesis XSD, an XML Schema to
// C++ data binding compiler.
//
// This program is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License version 2 as
// published by the Free Software Foundation.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program; if not, write to the Free Software
// Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
//
// In addition, as a special exception, Code Synthesis Tools CC gives
// permission to link this program with the Xerces-C++ library (or with
// modified versions of Xerces-C++ that use the same license as Xerces-C++),
// and distribute linked combinations including the two. You must obey
// the GNU General Public License version 2 in all respects for all of
// the code used other than Xerces-C++. If you modify this copy of the
// program, you may extend this exception to your version of the program,
// but you are not obligated to do so. If you do not wish to do so, delete
// this exception statement from your version.
//
// Furthermore, Code Synthesis Tools CC makes a special exception for
// the Free/Libre and Open Source Software (FLOSS) which is described
// in the accompanying FLOSSE file.
//

// Begin prologue.
//
//
// End prologue.

#include <xsd/cxx/pre.hxx>

#include "Discrete.hxx"

namespace cs
{
  // DiscreteType
  // 

  const DiscreteType::Status_type& DiscreteType::
  Status () const
  {
    return this->Status_.get ();
  }

  DiscreteType::Status_type& DiscreteType::
  Status ()
  {
    return this->Status_.get ();
  }

  void DiscreteType::
  Status (const Status_type& x)
  {
    this->Status_.set (x);
  }

  const DiscreteType::Name_type& DiscreteType::
  Name () const
  {
    return this->Name_.get ();
  }

  DiscreteType::Name_type& DiscreteType::
  Name ()
  {
    return this->Name_.get ();
  }

  void DiscreteType::
  Name (const Name_type& x)
  {
    this->Name_.set (x);
  }

  void DiscreteType::
  Name (::std::auto_ptr< Name_type > x)
  {
    this->Name_.set (x);
  }

  const DiscreteType::Description_optional& DiscreteType::
  Description () const
  {
    return this->Description_;
  }

  DiscreteType::Description_optional& DiscreteType::
  Description ()
  {
    return this->Description_;
  }

  void DiscreteType::
  Description (const Description_type& x)
  {
    this->Description_.set (x);
  }

  void DiscreteType::
  Description (const Description_optional& x)
  {
    this->Description_ = x;
  }

  void DiscreteType::
  Description (::std::auto_ptr< Description_type > x)
  {
    this->Description_.set (x);
  }

  const DiscreteType::id_optional& DiscreteType::
  id () const
  {
    return this->id_;
  }

  DiscreteType::id_optional& DiscreteType::
  id ()
  {
    return this->id_;
  }

  void DiscreteType::
  id (const id_type& x)
  {
    this->id_.set (x);
  }

  void DiscreteType::
  id (const id_optional& x)
  {
    this->id_ = x;
  }

  void DiscreteType::
  id (::std::auto_ptr< id_type > x)
  {
    this->id_.set (x);
  }


  // DiscreteList
  // 

  const DiscreteList::DISCRETE_sequence& DiscreteList::
  DISCRETE () const
  {
    return this->DISCRETE_;
  }

  DiscreteList::DISCRETE_sequence& DiscreteList::
  DISCRETE ()
  {
    return this->DISCRETE_;
  }

  void DiscreteList::
  DISCRETE (const DISCRETE_sequence& s)
  {
    this->DISCRETE_ = s;
  }
}

#include <xsd/cxx/xml/dom/parsing-source.hxx>

namespace cs
{
  // DiscreteType
  //

  DiscreteType::
  DiscreteType (const Status_type& Status,
                const Name_type& Name)
  : ::xml_schema::type (),
    Status_ (Status, ::xml_schema::flags (), this),
    Name_ (Name, ::xml_schema::flags (), this),
    Description_ (::xml_schema::flags (), this),
    id_ (::xml_schema::flags (), this)
  {
  }

  DiscreteType::
  DiscreteType (const DiscreteType& x,
                ::xml_schema::flags f,
                ::xml_schema::container* c)
  : ::xml_schema::type (x, f, c),
    Status_ (x.Status_, f, this),
    Name_ (x.Name_, f, this),
    Description_ (x.Description_, f, this),
    id_ (x.id_, f, this)
  {
  }

  DiscreteType::
  DiscreteType (const ::xercesc::DOMElement& e,
                ::xml_schema::flags f,
                ::xml_schema::container* c)
  : ::xml_schema::type (e, f | ::xml_schema::flags::base, c),
    Status_ (f, this),
    Name_ (f, this),
    Description_ (f, this),
    id_ (f, this)
  {
    if ((f & ::xml_schema::flags::base) == 0)
    {
      ::xsd::cxx::xml::dom::parser< char > p (e, true, true);
      this->parse (p, f);
    }
  }

  void DiscreteType::
  parse (::xsd::cxx::xml::dom::parser< char >& p,
         ::xml_schema::flags f)
  {
    for (; p.more_elements (); p.next_element ())
    {
      const ::xercesc::DOMElement& i (p.cur_element ());
      const ::xsd::cxx::xml::qualified_name< char > n (
        ::xsd::cxx::xml::dom::name< char > (i));

      // Status
      //
      if (n.name () == "Status" && n.namespace_ ().empty ())
      {
        if (!Status_.present ())
        {
          this->Status_.set (Status_traits::create (i, f, this));
          continue;
        }
      }

      // Name
      //
      if (n.name () == "Name" && n.namespace_ ().empty ())
      {
        ::std::auto_ptr< Name_type > r (
          Name_traits::create (i, f, this));

        if (!Name_.present ())
        {
          this->Name_.set (r);
          continue;
        }
      }

      // Description
      //
      if (n.name () == "Description" && n.namespace_ ().empty ())
      {
        ::std::auto_ptr< Description_type > r (
          Description_traits::create (i, f, this));

        if (!this->Description_)
        {
          this->Description_.set (r);
          continue;
        }
      }

      break;
    }

    if (!Status_.present ())
    {
      throw ::xsd::cxx::tree::expected_element< char > (
        "Status",
        "");
    }

    if (!Name_.present ())
    {
      throw ::xsd::cxx::tree::expected_element< char > (
        "Name",
        "");
    }

    while (p.more_attributes ())
    {
      const ::xercesc::DOMAttr& i (p.next_attribute ());
      const ::xsd::cxx::xml::qualified_name< char > n (
        ::xsd::cxx::xml::dom::name< char > (i));

      if (n.name () == "id" && n.namespace_ ().empty ())
      {
        ::std::auto_ptr< id_type > r (
          id_traits::create (i, f, this));

        this->id_.set (r);
        continue;
      }
    }
  }

  DiscreteType* DiscreteType::
  _clone (::xml_schema::flags f,
          ::xml_schema::container* c) const
  {
    return new class DiscreteType (*this, f, c);
  }

  DiscreteType::
  ~DiscreteType ()
  {
  }

  // DiscreteList
  //

  DiscreteList::
  DiscreteList ()
  : ::xml_schema::type (),
    DISCRETE_ (::xml_schema::flags (), this)
  {
  }

  DiscreteList::
  DiscreteList (const DiscreteList& x,
                ::xml_schema::flags f,
                ::xml_schema::container* c)
  : ::xml_schema::type (x, f, c),
    DISCRETE_ (x.DISCRETE_, f, this)
  {
  }

  DiscreteList::
  DiscreteList (const ::xercesc::DOMElement& e,
                ::xml_schema::flags f,
                ::xml_schema::container* c)
  : ::xml_schema::type (e, f | ::xml_schema::flags::base, c),
    DISCRETE_ (f, this)
  {
    if ((f & ::xml_schema::flags::base) == 0)
    {
      ::xsd::cxx::xml::dom::parser< char > p (e, true, false);
      this->parse (p, f);
    }
  }

  void DiscreteList::
  parse (::xsd::cxx::xml::dom::parser< char >& p,
         ::xml_schema::flags f)
  {
    for (; p.more_elements (); p.next_element ())
    {
      const ::xercesc::DOMElement& i (p.cur_element ());
      const ::xsd::cxx::xml::qualified_name< char > n (
        ::xsd::cxx::xml::dom::name< char > (i));

      // DISCRETE
      //
      if (n.name () == "DISCRETE" && n.namespace_ ().empty ())
      {
        ::std::auto_ptr< DISCRETE_type > r (
          DISCRETE_traits::create (i, f, this));

        this->DISCRETE_.push_back (r);
        continue;
      }

      break;
    }
  }

  DiscreteList* DiscreteList::
  _clone (::xml_schema::flags f,
          ::xml_schema::container* c) const
  {
    return new class DiscreteList (*this, f, c);
  }

  DiscreteList::
  ~DiscreteList ()
  {
  }
}

#include <istream>
#include <xsd/cxx/xml/sax/std-input-source.hxx>
#include <xsd/cxx/tree/error-handler.hxx>

namespace cs
{
  ::std::auto_ptr< ::cs::DiscreteList >
  DiscreteList_ (const ::std::string& u,
                 ::xml_schema::flags f,
                 const ::xml_schema::properties& p)
  {
    ::xsd::cxx::xml::auto_initializer i (
      (f & ::xml_schema::flags::dont_initialize) == 0,
      (f & ::xml_schema::flags::keep_dom) == 0);

    ::xsd::cxx::tree::error_handler< char > h;

    ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > d (
      ::xsd::cxx::xml::dom::parse< char > (
        u, h, p, f));

    h.throw_if_failed< ::xsd::cxx::tree::parsing< char > > ();

    ::std::auto_ptr< ::cs::DiscreteList > r (
      ::cs::DiscreteList_ (
        d, f | ::xml_schema::flags::own_dom, p));

    return r;
  }

  ::std::auto_ptr< ::cs::DiscreteList >
  DiscreteList_ (const ::std::string& u,
                 ::xml_schema::error_handler& h,
                 ::xml_schema::flags f,
                 const ::xml_schema::properties& p)
  {
    ::xsd::cxx::xml::auto_initializer i (
      (f & ::xml_schema::flags::dont_initialize) == 0,
      (f & ::xml_schema::flags::keep_dom) == 0);

    ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > d (
      ::xsd::cxx::xml::dom::parse< char > (
        u, h, p, f));

    if (!d.get ())
      throw ::xsd::cxx::tree::parsing< char > ();

    ::std::auto_ptr< ::cs::DiscreteList > r (
      ::cs::DiscreteList_ (
        d, f | ::xml_schema::flags::own_dom, p));

    return r;
  }

  ::std::auto_ptr< ::cs::DiscreteList >
  DiscreteList_ (const ::std::string& u,
                 ::xercesc::DOMErrorHandler& h,
                 ::xml_schema::flags f,
                 const ::xml_schema::properties& p)
  {
    ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > d (
      ::xsd::cxx::xml::dom::parse< char > (
        u, h, p, f));

    if (!d.get ())
      throw ::xsd::cxx::tree::parsing< char > ();

    ::std::auto_ptr< ::cs::DiscreteList > r (
      ::cs::DiscreteList_ (
        d, f | ::xml_schema::flags::own_dom, p));

    return r;
  }

  ::std::auto_ptr< ::cs::DiscreteList >
  DiscreteList_ (::std::istream& is,
                 ::xml_schema::flags f,
                 const ::xml_schema::properties& p)
  {
    ::xsd::cxx::xml::auto_initializer i (
      (f & ::xml_schema::flags::dont_initialize) == 0,
      (f & ::xml_schema::flags::keep_dom) == 0);

    ::xsd::cxx::xml::sax::std_input_source isrc (is);
    return ::cs::DiscreteList_ (isrc, f, p);
  }

  ::std::auto_ptr< ::cs::DiscreteList >
  DiscreteList_ (::std::istream& is,
                 ::xml_schema::error_handler& h,
                 ::xml_schema::flags f,
                 const ::xml_schema::properties& p)
  {
    ::xsd::cxx::xml::auto_initializer i (
      (f & ::xml_schema::flags::dont_initialize) == 0,
      (f & ::xml_schema::flags::keep_dom) == 0);

    ::xsd::cxx::xml::sax::std_input_source isrc (is);
    return ::cs::DiscreteList_ (isrc, h, f, p);
  }

  ::std::auto_ptr< ::cs::DiscreteList >
  DiscreteList_ (::std::istream& is,
                 ::xercesc::DOMErrorHandler& h,
                 ::xml_schema::flags f,
                 const ::xml_schema::properties& p)
  {
    ::xsd::cxx::xml::sax::std_input_source isrc (is);
    return ::cs::DiscreteList_ (isrc, h, f, p);
  }

  ::std::auto_ptr< ::cs::DiscreteList >
  DiscreteList_ (::std::istream& is,
                 const ::std::string& sid,
                 ::xml_schema::flags f,
                 const ::xml_schema::properties& p)
  {
    ::xsd::cxx::xml::auto_initializer i (
      (f & ::xml_schema::flags::dont_initialize) == 0,
      (f & ::xml_schema::flags::keep_dom) == 0);

    ::xsd::cxx::xml::sax::std_input_source isrc (is, sid);
    return ::cs::DiscreteList_ (isrc, f, p);
  }

  ::std::auto_ptr< ::cs::DiscreteList >
  DiscreteList_ (::std::istream& is,
                 const ::std::string& sid,
                 ::xml_schema::error_handler& h,
                 ::xml_schema::flags f,
                 const ::xml_schema::properties& p)
  {
    ::xsd::cxx::xml::auto_initializer i (
      (f & ::xml_schema::flags::dont_initialize) == 0,
      (f & ::xml_schema::flags::keep_dom) == 0);

    ::xsd::cxx::xml::sax::std_input_source isrc (is, sid);
    return ::cs::DiscreteList_ (isrc, h, f, p);
  }

  ::std::auto_ptr< ::cs::DiscreteList >
  DiscreteList_ (::std::istream& is,
                 const ::std::string& sid,
                 ::xercesc::DOMErrorHandler& h,
                 ::xml_schema::flags f,
                 const ::xml_schema::properties& p)
  {
    ::xsd::cxx::xml::sax::std_input_source isrc (is, sid);
    return ::cs::DiscreteList_ (isrc, h, f, p);
  }

  ::std::auto_ptr< ::cs::DiscreteList >
  DiscreteList_ (::xercesc::InputSource& i,
                 ::xml_schema::flags f,
                 const ::xml_schema::properties& p)
  {
    ::xsd::cxx::tree::error_handler< char > h;

    ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > d (
      ::xsd::cxx::xml::dom::parse< char > (
        i, h, p, f));

    h.throw_if_failed< ::xsd::cxx::tree::parsing< char > > ();

    ::std::auto_ptr< ::cs::DiscreteList > r (
      ::cs::DiscreteList_ (
        d, f | ::xml_schema::flags::own_dom, p));

    return r;
  }

  ::std::auto_ptr< ::cs::DiscreteList >
  DiscreteList_ (::xercesc::InputSource& i,
                 ::xml_schema::error_handler& h,
                 ::xml_schema::flags f,
                 const ::xml_schema::properties& p)
  {
    ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > d (
      ::xsd::cxx::xml::dom::parse< char > (
        i, h, p, f));

    if (!d.get ())
      throw ::xsd::cxx::tree::parsing< char > ();

    ::std::auto_ptr< ::cs::DiscreteList > r (
      ::cs::DiscreteList_ (
        d, f | ::xml_schema::flags::own_dom, p));

    return r;
  }

  ::std::auto_ptr< ::cs::DiscreteList >
  DiscreteList_ (::xercesc::InputSource& i,
                 ::xercesc::DOMErrorHandler& h,
                 ::xml_schema::flags f,
                 const ::xml_schema::properties& p)
  {
    ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > d (
      ::xsd::cxx::xml::dom::parse< char > (
        i, h, p, f));

    if (!d.get ())
      throw ::xsd::cxx::tree::parsing< char > ();

    ::std::auto_ptr< ::cs::DiscreteList > r (
      ::cs::DiscreteList_ (
        d, f | ::xml_schema::flags::own_dom, p));

    return r;
  }

  ::std::auto_ptr< ::cs::DiscreteList >
  DiscreteList_ (const ::xercesc::DOMDocument& d,
                 ::xml_schema::flags f,
                 const ::xml_schema::properties& p)
  {
    if (f & ::xml_schema::flags::keep_dom)
    {
      ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > c (
        static_cast< ::xercesc::DOMDocument* > (d.cloneNode (true)));

      ::std::auto_ptr< ::cs::DiscreteList > r (
        ::cs::DiscreteList_ (
          c, f | ::xml_schema::flags::own_dom, p));

      return r;
    }

    const ::xercesc::DOMElement& e (*d.getDocumentElement ());
    const ::xsd::cxx::xml::qualified_name< char > n (
      ::xsd::cxx::xml::dom::name< char > (e));

    if (n.name () == "DiscreteList" &&
        n.namespace_ () == "")
    {
      ::std::auto_ptr< ::cs::DiscreteList > r (
        ::xsd::cxx::tree::traits< ::cs::DiscreteList, char >::create (
          e, f, 0));
      return r;
    }

    throw ::xsd::cxx::tree::unexpected_element < char > (
      n.name (),
      n.namespace_ (),
      "DiscreteList",
      "");
  }

  ::std::auto_ptr< ::cs::DiscreteList >
  DiscreteList_ (::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument >& d,
                 ::xml_schema::flags f,
                 const ::xml_schema::properties&)
  {
    ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > c (
      ((f & ::xml_schema::flags::keep_dom) &&
       !(f & ::xml_schema::flags::own_dom))
      ? static_cast< ::xercesc::DOMDocument* > (d->cloneNode (true))
      : 0);

    ::xercesc::DOMDocument& doc (c.get () ? *c : *d);
    const ::xercesc::DOMElement& e (*doc.getDocumentElement ());

    const ::xsd::cxx::xml::qualified_name< char > n (
      ::xsd::cxx::xml::dom::name< char > (e));

    if (f & ::xml_schema::flags::keep_dom)
      doc.setUserData (::xml_schema::dom::tree_node_key,
                       (c.get () ? &c : &d),
                       0);

    if (n.name () == "DiscreteList" &&
        n.namespace_ () == "")
    {
      ::std::auto_ptr< ::cs::DiscreteList > r (
        ::xsd::cxx::tree::traits< ::cs::DiscreteList, char >::create (
          e, f, 0));
      return r;
    }

    throw ::xsd::cxx::tree::unexpected_element < char > (
      n.name (),
      n.namespace_ (),
      "DiscreteList",
      "");
  }
}

#include <ostream>
#include <xsd/cxx/tree/error-handler.hxx>
#include <xsd/cxx/xml/dom/serialization-source.hxx>

namespace cs
{
  void
  DiscreteList_ (::std::ostream& o,
                 const ::cs::DiscreteList& s,
                 const ::xml_schema::namespace_infomap& m,
                 const ::std::string& e,
                 ::xml_schema::flags f)
  {
    ::xsd::cxx::xml::auto_initializer i (
      (f & ::xml_schema::flags::dont_initialize) == 0);

    ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > d (
      ::cs::DiscreteList_ (s, m, f));

    ::xsd::cxx::tree::error_handler< char > h;

    ::xsd::cxx::xml::dom::ostream_format_target t (o);
    if (!::xsd::cxx::xml::dom::serialize (t, *d, e, h, f))
    {
      h.throw_if_failed< ::xsd::cxx::tree::serialization< char > > ();
    }
  }

  void
  DiscreteList_ (::std::ostream& o,
                 const ::cs::DiscreteList& s,
                 ::xml_schema::error_handler& h,
                 const ::xml_schema::namespace_infomap& m,
                 const ::std::string& e,
                 ::xml_schema::flags f)
  {
    ::xsd::cxx::xml::auto_initializer i (
      (f & ::xml_schema::flags::dont_initialize) == 0);

    ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > d (
      ::cs::DiscreteList_ (s, m, f));
    ::xsd::cxx::xml::dom::ostream_format_target t (o);
    if (!::xsd::cxx::xml::dom::serialize (t, *d, e, h, f))
    {
      throw ::xsd::cxx::tree::serialization< char > ();
    }
  }

  void
  DiscreteList_ (::std::ostream& o,
                 const ::cs::DiscreteList& s,
                 ::xercesc::DOMErrorHandler& h,
                 const ::xml_schema::namespace_infomap& m,
                 const ::std::string& e,
                 ::xml_schema::flags f)
  {
    ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > d (
      ::cs::DiscreteList_ (s, m, f));
    ::xsd::cxx::xml::dom::ostream_format_target t (o);
    if (!::xsd::cxx::xml::dom::serialize (t, *d, e, h, f))
    {
      throw ::xsd::cxx::tree::serialization< char > ();
    }
  }

  void
  DiscreteList_ (::xercesc::XMLFormatTarget& t,
                 const ::cs::DiscreteList& s,
                 const ::xml_schema::namespace_infomap& m,
                 const ::std::string& e,
                 ::xml_schema::flags f)
  {
    ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > d (
      ::cs::DiscreteList_ (s, m, f));

    ::xsd::cxx::tree::error_handler< char > h;

    if (!::xsd::cxx::xml::dom::serialize (t, *d, e, h, f))
    {
      h.throw_if_failed< ::xsd::cxx::tree::serialization< char > > ();
    }
  }

  void
  DiscreteList_ (::xercesc::XMLFormatTarget& t,
                 const ::cs::DiscreteList& s,
                 ::xml_schema::error_handler& h,
                 const ::xml_schema::namespace_infomap& m,
                 const ::std::string& e,
                 ::xml_schema::flags f)
  {
    ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > d (
      ::cs::DiscreteList_ (s, m, f));
    if (!::xsd::cxx::xml::dom::serialize (t, *d, e, h, f))
    {
      throw ::xsd::cxx::tree::serialization< char > ();
    }
  }

  void
  DiscreteList_ (::xercesc::XMLFormatTarget& t,
                 const ::cs::DiscreteList& s,
                 ::xercesc::DOMErrorHandler& h,
                 const ::xml_schema::namespace_infomap& m,
                 const ::std::string& e,
                 ::xml_schema::flags f)
  {
    ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > d (
      ::cs::DiscreteList_ (s, m, f));
    if (!::xsd::cxx::xml::dom::serialize (t, *d, e, h, f))
    {
      throw ::xsd::cxx::tree::serialization< char > ();
    }
  }

  void
  DiscreteList_ (::xercesc::DOMDocument& d,
                 const ::cs::DiscreteList& s,
                 ::xml_schema::flags)
  {
    ::xercesc::DOMElement& e (*d.getDocumentElement ());
    const ::xsd::cxx::xml::qualified_name< char > n (
      ::xsd::cxx::xml::dom::name< char > (e));

    if (n.name () == "DiscreteList" &&
        n.namespace_ () == "")
    {
      e << s;
    }
    else
    {
      throw ::xsd::cxx::tree::unexpected_element < char > (
        n.name (),
        n.namespace_ (),
        "DiscreteList",
        "");
    }
  }

  ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument >
  DiscreteList_ (const ::cs::DiscreteList& s,
                 const ::xml_schema::namespace_infomap& m,
                 ::xml_schema::flags f)
  {
    ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > d (
      ::xsd::cxx::xml::dom::serialize< char > (
        "DiscreteList",
        "",
        m, f));

    ::cs::DiscreteList_ (*d, s, f);
    return d;
  }

  void
  operator<< (::xercesc::DOMElement& e, const DiscreteType& i)
  {
    e << static_cast< const ::xml_schema::type& > (i);

    // Status
    //
    {
      ::xercesc::DOMElement& s (
        ::xsd::cxx::xml::dom::create_element (
          "Status",
          e));

      s << i.Status ();
    }

    // Name
    //
    {
      ::xercesc::DOMElement& s (
        ::xsd::cxx::xml::dom::create_element (
          "Name",
          e));

      s << i.Name ();
    }

    // Description
    //
    if (i.Description ())
    {
      ::xercesc::DOMElement& s (
        ::xsd::cxx::xml::dom::create_element (
          "Description",
          e));

      s << *i.Description ();
    }

    // id
    //
    if (i.id ())
    {
      ::xercesc::DOMAttr& a (
        ::xsd::cxx::xml::dom::create_attribute (
          "id",
          e));

      a << *i.id ();
    }
  }

  void
  operator<< (::xercesc::DOMElement& e, const DiscreteList& i)
  {
    e << static_cast< const ::xml_schema::type& > (i);

    // DISCRETE
    //
    for (DiscreteList::DISCRETE_const_iterator
         b (i.DISCRETE ().begin ()), n (i.DISCRETE ().end ());
         b != n; ++b)
    {
      ::xercesc::DOMElement& s (
        ::xsd::cxx::xml::dom::create_element (
          "DISCRETE",
          e));

      s << *b;
    }
  }
}

#include <xsd/cxx/post.hxx>

// Begin epilogue.
//
//
// End epilogue.

