//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : SIMP.h
//  @ Date : 08/06/2012
//  Author: Emanuele Galli
//
//


#if !defined(_SIMP_H)
#define _SIMP_H

#include "TSAP.h"



/*!
 * \class SIMP
 * SIMP controller
 * Derives from TSAP class
 */
class SIMP  : public TSAP{
public:

	/*!
	 * Default Constructor. Sets SGA with sga parameters, default base address and RAM size
	 * @param sga SGA Address
	 */
	SIMP(VmeAbstractionDevice *adapter, EN_SGA_ADDRESS sga = EN_SGA_2);

	virtual ~SIMP(){};

	//void setRTmode();
	//void setBCmode();
	//unsigned int read(unsigned int address);
	//void write(unsigned int data, unsigned int address);
	UINT32 execTest(const TestStruct& test);
	void initBoard();

private:
	void initSIMPBoard();
};

#endif  //_SIMP_H
